name: Deploy
on:
 push:
  branches: [main]

jobs:
 Deploy:
   name: "deploy to EC2"
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - name: install script
      run: |
       echo " we aren't doing much yet"
      

