name: Deploy
on:
 push:
  branches: [main]

env:
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  Create_EC2:
   runs-on: ubuntu-latest
   steps:
     - name: checkout code from repo
       uses: actions/checkout@v4

     - name: Setup Terraform to implement Cloud Infra
       uses: hashicorp/setup-terraform@v2
       with: 
         terraform_version: 1.3.0

     - name: Terraform init
       run: terraform init
  
     - name: Terraform Plan
       run: terraform plan
  
     - name: Terraform Apply
       run: terraform apply --auto-approve

  # Deploy:
  #  name: "deploy to EC2"
  #  runs-on: ubuntu-latest
  #  steps:
  #   - uses: actions/checkout@v2
  #   - name: install script
  #     env:
  #       PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  #     run: |
  #      echo "$PRIVATE_KEY" > sunday.pem && chmod 600 sunday.pem
  #      echo "copy readme file to the target node"
  #      scp -o StrictHostKeyChecking=no -i sunday.pem README.md ec2-user@18.171.150.211:~/
  #      echo  "connecting to the box and install a couple of apps"
  #      ssh -o StrictHostKeyChecking=no -i sunday.pem ec2-user@18.171.150.211 '
  #      sudo yum install git -y
  #      sudo yum install nginx -y
  #      sudo service nginx start
  #      '
      

