name: Deploy
on:
 push:
  branches: [main]

jobs:
 Deploy:
   name: "deploy to EC2"
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - name: install script
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
       echo "$PRIVATE_KEY" > sunday.pem && chmod 600 sunday.pem
       echo "copy readme file to the target node"
       scp -o StrictHostKeyChecking=no -i sunday.pem README.md ec2-user@18.171.150.211:~/
       echo  "connecting to the box and install a couple of apps"
       ssh -o StrictHostKeyChecking=no -i sunday.pem ec2-user@18.171.150.211 '
       sudo yum install git -y
       sudo yum install nginx -y
       sudo service nginx start
       '
      

